module.exports = {
    Speciality : require('./Speciality.model'),
    Advertisement :  require('./Advertisement.model'),
    Faq: require('./Faq.model'),
    Slot: require('./Slot.model'),
    Admin: require('./Admin.model'),
    City: require('./City.model'),
    Appointment: require('./Appointment.model'),
    SocialLinks : require('./SocialLinks.model'),
    Newsletters : require('./newsletter.model'),
    AdminSettings: require('./AdminSettings.model'),
    Category: require('./Category.model'),
    Otp: require('./Otp.model'),
    Page: require('./Page.model'),
    User: require('./User.model'),
    Payment: require('./Payment.model'),
    Notification: require('./Notification.model'),
    PaymentRequest: require('./PaymentRequest.model'),
    Chat: require('./Chat.model'),
    Message: require('./Message.model'),
    FriendRequest: require('./FriendRequest.model'),
    Country: require('./Country.model'),
    State: require('./State.model'),
    BecomeVerifiedRequest: require('./BecomeVerifiedRequest.model'),
    //social media
    Feed: require('./Feed.model'),
    FeedReport: require('./FeedReport.model'),
    FeedLike: require('./FeedLike.model'),
    FeedComment: require('./FeedComment.model'),
    Webinar: require('./Webinar.model'),
    Blog: require('./Blog.model'),
    OrganizationRequest: require("./OrganizationRequest.model"),
    Organization: require("./Organization.model"),
    Banner: require("./Banner.model"),
    AgendaJob: require("./AgendaJob.model"),
    WebinarRecord: require("./WebinarRecord.model"),
    Call: require('./Call.model'),
    PreWallet: require("./PreWallet.model"),
    DirectCall: require("./DirectCall.model"),
    Documents: require("./Documents.model"),
    Referral: require("./Referral.model"),
    
};
